ARG APP_CODE_WORKDIR=${APP_CODE_WORKDIR}
ARG NODE_VERSION=${NODE_VERSION}
ARG APP_PORT=${APP_PORT}

FROM node:${NODE_VERSION}-alpine

#RUN apk update && \
#    apk add git openjdk11-jre-headless bash
#
#RUN npm install -g firebase-tools

WORKDIR /src

# EXPOSE 3000 4000 5000 5001 9000 8080 8085 9099
EXPOSE 3000
