up:
	docker-compose up -d

build:
	docker-compose build

stop:
	docker-compose stop

bash-api:
	docker exec -it go_vue_typescript_api sh

bash-app:
	docker exec -it nuxt_firebase_app sh
bash-mysql:
	docker exec -it go_vue_typescript_api sh
